[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci',
  'ls -la',
  'echo "Copying frontend files..."',
  'cp -r frontend/* .',
  'ls -la'
]

[phases.build]
cmds = [
  'echo "Frontend files in root:"',
  'ls -la *.html',
  'echo "Building application..."'
]

[start]
cmd = 'npm run start'
