FROM node:18.20.3-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# Skip frontend build since it has none
# RUN npm run build --prefix frontend

CMD ["npm", "run", "dev", "--prefix", "backend"]
