name: Deploy Kongle

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Installer dependencies
        run: npm ci

      - name: Bygg prosjektet (om nødvendig)
        run: npm run build # Kommenter ut hvis ikke brukt

      - name: Deploy til server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/your/app
            git pull origin main
            npm ci --production
            pm2 restart kongle --update-env || pm2 start server.js --name kongle --log-date-format "YYYY-MM-DD HH:mm" --output /var/log/kongle/out.log --error /var/log/kongle/error.log
